---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: zigbee
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  cooldownPeriod: 0
  minReplicaCount: 0
  maxReplicaCount: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zigbee
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
        query: count(kube_node_labels{label_nabu_casa_feature_node_kubernetes_io_zbt_2="true"}) or vector(0)
        threshold: "1"
        ignoreNullValues: "0"
