---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autopulse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: autopulse-secret
    template:
      templateFrom:
        - configMap:
            name: autopulse-configmap
            items:
              - key: config.yaml
  dataFrom:
    - extract:
        key: autopulse
    - extract:
        key: plex
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autopulse-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: autopulse-db-secret
    template:
      data:
        INIT_POSTGRES_DBNAME: "{{ .AUTOPULSE_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: "{{ .INIT_POSTGRES_HOST }}"
        INIT_POSTGRES_USER: "{{ .AUTOPULSE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .AUTOPULSE_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .INIT_POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: autopulse
