---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: mac(link.permanent_addr) == "cc:28:aa:47:a5:56"
# ---
# apiVersion: v1alpha1
# kind: BondConfig
# name: bond0
# links: [net0]
# bondMode: active-backup
# up: true
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: net0
---
apiVersion: v1alpha1
kind: VLANConfig
name: net0.70
vlanID: 70
parent: net0
---
apiVersion: v1alpha1
kind: VLANConfig
name: net0.90
vlanID: 90
parent: net0
---
apiVersion: v1alpha1
kind: TimeSyncConfig
ntp:
  servers:
    - 162.159.200.1
    - 162.159.200.123
