libraries:
  Anime:
    collection_files:
      - default: basic
    overlay_files:
      - default: status
  Movies:
    collection_files:
      - default: aspect
      - default: based
      - default: basic
      - default: collectionless
      - default: content_rating_au
      - default: country
        template_variables: &country_vars
          include:
            - Australia
            - Italy
            - Russia
      - default: emmy
      - default: golden
      - default: oscars
      - default: resolution
      - default: seasonal
      - default: streaming
        template_variables: &streaming_vars
          originals_only: true
          exclude:
            - atresplayer
            - bet
            - channel4
            - crave
            - crunchyroll
            - filmin
            - hayu
            - itvx
            - movistar
            - tubi
          style: "white"
      - default: studio
        template_variables:
          sort_by: release.asc
          item_radarr_tag_pixar: "pixar"
          item_sonarr_tag_pixar: "pixar"
      - default: tmdb
      - default: universe
    overlay_files:
      - default: status
  "TV Shows":
    collection_files:
      - default: aspect
      - default: based
      - default: basic
      - default: collectionless
      - default: content_rating_au
      - default: country
        template_variables: *country_vars
      - default: emmy
      - default: golden
      - default: network
      - default: resolution
      - default: streaming
        template_variables: *streaming_vars
      - default: tmdb
      - default: universe
    overlay_files:
      - default: status
      - default: aspect
      - default: audio_codec
      - default: resolution
  "Фильмы":
    collection_files:
      - default: basic
      - default: streaming

plex:
  url: http://plex.default.svc.cluster.local:32400
  token: <<PLEX_API_KEY>>

tmdb:
  apikey: <<TMDB_API_KEY>>

settings:
  delete_below_minimum: true
  minimum_items: 2
  overlay_artwork_filetype: webp_lossless
