libraries:
  Anime:
    collection_files:
      - default: basic
      - default: network
      - default: streaming
    overlay_files:
      - default: status
  Movies:
    collection_files:
      - default: aspect
      - default: based
      - default: basic
      - default: collectionless
      - default: content_rating_au
      - default: country
        template_variables: &country_vars
          include:
            - Australia
            - Italy
            - Russia
      - default: emmy
      - default: golden
      - default: oscars
      - default: resolution
      - default: seasonal
      - default: streaming
        template_variables: &streaming_vars
          originals_only: true
          exclude:
            - atresplayer
            - bet
            - channel4
            - crave
            - crunchyroll
            - filmin
            - hayu
            - itvx
            - movistar
            - tubi
          style: "white"
      - default: tmdb
      - default: universe
  "TV Shows":
    collection_files:
      - default: aspect
      - default: based
      - default: basic
      - default: collectionless
      - default: content_rating_au
      - default: country
        template_variables: *country_vars
      - default: emmy
      - default: golden
      - default: network
      - default: resolution
      - default: streaming
        template_variables: *streaming_vars
      - default: tmdb
      - default: universe
    overlay_files:
      - default: content_rating_au
      - default: status
      - default: aspect
      - default: audio_codec
      - default: resolution
      - default: network
      - default: streaming
      - default: studio
  "Фильмы":
    collection_files:
      - default: basic
      - default: streaming

plex:
  url: http://plex.default.svc.cluster.local:32400
  token: <<PLEX_API_KEY>>

tmdb:
  apikey: <<TMDB_API_KEY>>

settings:
  delete_below_minimum: true
  minimum_items: 2
  overlay_artwork_filetype: webp_lossless

radarr:
  url: http://radarr.default.svc.cluster.local
  token: <<RADARR_API_KEY>>
  add_missing: false
  add_existing: false
  upgrade_existing: true
  monitor_existing: true
  monitor: false
  availability: released
  quality_profile: "[SQP] SQP-1 (2160p)"
  tag: kometa
  search: false
