#!/usr/bin/env bash
#
# Rotate FLUX_GITHUB_TOKEN, the token Flux's github-status Provider uses to post
# commit statuses to igas/home-ops. Checks the current token first and stops if
# it still works. Run it with `task github-status-token`.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: rotate the GitHub token Flux uses for commit statuses.
# ──────────────────────────────────────────────────────────────────────────

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export KUBECONFIG="${KUBECONFIG:-$ROOT_DIR/kubeconfig}"
ENV_FILE=/dev/null # the token lives in 1Password only, never on disk

REPO="igas/home-ops"
OP_VAULT="Kubernetes"
OP_ITEM="flux"
OP_FIELD="FLUX_GITHUB_TOKEN"
ES_NAME="github-status-token"
SECRET_NAME="github-status-token-secret"

# gh_probe TOKEN PATH sets PROBE_CODE and PROBE_EXPIRY for a GitHub API GET.
# The header goes in on stdin so the token never shows up in `ps`.
gh_probe() {
  local headers
  headers=$(printf 'Authorization: Bearer %s\n' "$1" |
    curl -sS -o /dev/null -D - -H @- -H 'Accept: application/vnd.github+json' \
      "https://api.github.com$2" 2>/dev/null || true)
  PROBE_CODE=$(awk 'NR==1 {print $2}' <<<"$headers")
  PROBE_EXPIRY=$(grep -i '^github-authentication-token-expiration:' <<<"$headers" |
    cut -d' ' -f2- | tr -d '\r' || true)
}

# token_kind TOKEN names the token type from its prefix.
token_kind() {
  case "$1" in
    github_pat_*) echo "fine-grained PAT" ;;
    ghp_*)        echo "classic PAT" ;;
    gho_*)        echo "OAuth token" ;;
    "")           echo "empty" ;;
    *)            echo "not a recognised GitHub token format" ;;
  esac
}

# report_token LABEL TOKEN probes TOKEN and prints a summary; returns success
# when it can read commit statuses on $REPO.
report_token() {
  local label="$1" token="$2" user_code
  say "${BOLD}$label${RESET}: $(token_kind "$token")"
  [[ -n "$token" ]] || return 1
  gh_probe "$token" /user; user_code="$PROBE_CODE"
  note "GET /user                         → ${user_code:-no response}"
  [[ -n "$PROBE_EXPIRY" ]] && note "expires                           → $PROBE_EXPIRY"
  gh_probe "$token" "/repos/$REPO/commits/main/statuses"
  note "GET /repos/$REPO/…/statuses → ${PROBE_CODE:-no response}"
  [[ "$user_code" == 401 ]] && warn "GitHub rejects this token (401): expired, revoked or wrong"
  [[ "$PROBE_CODE" == 200 ]]
}

cluster_token() {
  kubectl -n "$1" get secret "$SECRET_NAME" -o jsonpath='{.data.token}' 2>/dev/null | base64 -d 2>/dev/null || true
}

for bin in kubectl flux op curl; do
  command -v "$bin" >/dev/null 2>&1 || { printf '%s is required\n' "$bin" >&2; exit 1; }
done

TOTAL_STAGES=7

banner "Flux GitHub commit-status token"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check the token the cluster uses now"
mapfile -t NAMESPACES < <(kubectl get externalsecret -A \
  --field-selector "metadata.name=$ES_NAME" -o jsonpath='{range .items[*]}{.metadata.namespace}{"\n"}{end}')
if (( ${#NAMESPACES[@]} == 0 )); then
  warn "no $ES_NAME ExternalSecrets found; is KUBECONFIG ($KUBECONFIG) right?"
  exit 1
fi
note "ExternalSecret $ES_NAME in: ${NAMESPACES[*]}"
printf '\n'
if report_token "Cluster secret ($SECRET_NAME in ${NAMESPACES[0]})" "$(cluster_token "${NAMESPACES[0]}")"; then
  printf '\n'
  say "${GREEN}The current token works.${RESET}"
  if ! confirm "Rotate it anyway?"; then
    finish; note "Nothing changed."; exit 0
  fi
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Sign in to 1Password"
say "The token is stored in 1Password: vault '$OP_VAULT', item '$OP_ITEM', field '$OP_FIELD'."
note "If the 1Password app is closed, open it first so the CLI can unlock."
if ! op whoami >/dev/null 2>&1; then
  eval "$(op signin)"
fi
op whoami >/dev/null 2>&1 || { warn "op is still not signed in"; exit 1; }
say "${GREEN}✓${RESET} signed in"
OP_TOKEN=$(op read "op://$OP_VAULT/$OP_ITEM/$OP_FIELD" 2>/dev/null || true)
printf '\n'
NEW_TOKEN=""
if [[ "$OP_TOKEN" == "$(cluster_token "${NAMESPACES[0]}")" ]]; then
  note "1Password holds the same token as the cluster."
elif report_token "1Password (differs from the cluster)" "$OP_TOKEN"; then
  printf '\n'
  say "${GREEN}1Password already holds a working token${RESET}; the cluster just hasn't synced it."
  if confirm "Use it and skip creating a new one?"; then NEW_TOKEN="$OP_TOKEN"; fi
fi
pause

if [[ -z "$NEW_TOKEN" ]]; then
  # ── 3 ───────────────────────────────────────────────────────────────────
  stage "Create a fine-grained token on GitHub"
  open_url "https://github.com/settings/personal-access-tokens/new"
  step "Token name: flux-github-status (home-ops)"
  step "Expiration: pick the longest you're comfortable with, then note the date"
  step "Resource owner: ${REPO%%/*}"
  step "Repository access: Only select repositories → ${REPO#*/}"
  step "Permissions → Repository: set Commit statuses to Read and write"
  note "  (Metadata: Read-only is added automatically; nothing else is needed)"
  step "Generate token, then copy it (starts github_pat_)"
  pause "Press Enter once it's copied"

  # ── 4 ───────────────────────────────────────────────────────────────────
  stage "Check the new token"
  while :; do
    ask_secret NEW_TOKEN "Paste the new token:"
    printf '\n'
    if report_token "New token" "$NEW_TOKEN"; then break; fi
    warn "This token can't read commit statuses on $REPO. Check the repo and permission, then paste again."
  done
  note "GitHub can't confirm write access without posting a status; stage 7 checks that."
  pause

  # ── 5 ───────────────────────────────────────────────────────────────────
  stage "Save it to 1Password"
  say "This overwrites $OP_FIELD in '$OP_VAULT/$OP_ITEM'. The old value stays in the item's history."
  if ! confirm "Write the new token to 1Password?"; then
    warn "Stopped before writing; nothing changed."; exit 1
  fi
  op item edit "$OP_ITEM" --vault "$OP_VAULT" "$OP_FIELD=$NEW_TOKEN" >/dev/null
  if [[ "$(op read "op://$OP_VAULT/$OP_ITEM/$OP_FIELD")" == "$NEW_TOKEN" ]]; then
    say "${GREEN}✓${RESET} 1Password updated"
  else
    warn "1Password read-back doesn't match; check the item by hand"; exit 1
  fi
  pause
else
  stage "Create a fine-grained token on GitHub"; note "skipped: 1Password already has a working token"
  stage "Check the new token";                   note "skipped"
  stage "Save it to 1Password";                  note "skipped"
  pause
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Sync the ExternalSecrets"
say "Forcing $ES_NAME to refresh now instead of waiting up to an hour."
stamp=$(date +%s)
for ns in "${NAMESPACES[@]}"; do
  kubectl -n "$ns" annotate externalsecret "$ES_NAME" "force-sync=$stamp" --overwrite >/dev/null
done
for ns in "${NAMESPACES[@]}"; do
  for _ in $(seq 30); do
    [[ "$(cluster_token "$ns")" == "$NEW_TOKEN" ]] && break
    sleep 2
  done
  if [[ "$(cluster_token "$ns")" == "$NEW_TOKEN" ]]; then
    say "${GREEN}✓${RESET} $ns"
  else
    warn "$ns: secret still holds the old token after 60s"
    SKIPPED+=("check: kubectl -n $ns describe externalsecret $ES_NAME")
  fi
done
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Confirm Flux posts commit statuses"
since=$(date -u +%Y-%m-%dT%H:%M:%SZ)
ks=$(kubectl -n "${NAMESPACES[0]}" get kustomizations.kustomize.toolkit.fluxcd.io -o jsonpath='{.items[0].metadata.name}')
sha=$(kubectl -n flux-system get gitrepository flux-system -o jsonpath='{.status.artifact.revision}')
sha="${sha##*:}"
say "Reconciling Kustomization ${NAMESPACES[0]}/$ks to trigger an event…"
flux -n "${NAMESPACES[0]}" reconcile kustomization "$ks" >/dev/null 2>&1 || warn "flux reconcile failed"
contexts=""
for _ in $(seq 20); do
  contexts=$(printf 'Authorization: Bearer %s\n' "$NEW_TOKEN" |
    curl -sS -H @- -H 'Accept: application/vnd.github+json' \
      "https://api.github.com/repos/$REPO/commits/$sha/statuses?per_page=100" 2>/dev/null |
    grep -o '"context": *"kustomization/[^"]*"' | sort -u || true)
  [[ -n "$contexts" ]] && break
  sleep 3
done
failures=$(kubectl -n flux-system logs deploy/notification-controller --since-time="$since" 2>/dev/null |
  grep -c 'failed to send notification' || true)
if [[ -n "$contexts" ]]; then
  say "${GREEN}✓${RESET} commit statuses on ${sha:0:7}:"
  while read -r c; do note "  ${c#*: }"; done <<<"$contexts"
else
  warn "no kustomization/* statuses on ${sha:0:7} yet"
  SKIPPED+=("check https://github.com/$REPO/commit/$sha for Flux statuses")
fi
if [[ "$failures" == 0 ]]; then
  say "${GREEN}✓${RESET} no 'failed to send notification' errors since $since"
else
  warn "$failures notification failure(s) since $since"
  SKIPPED+=("kubectl -n flux-system logs deploy/notification-controller --since-time=$since | grep 'failed to send'")
fi
pause "Press Enter to finish"

finish
if [[ -n "$PROBE_EXPIRY" ]]; then
  note "Token expires $PROBE_EXPIRY; re-run: task github-status-token"
fi
