---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
hardwareAddr: 4a:e7:25:61:d9:d6
links:
  - enp2s0
bondMode: active-backup
up: true
addresses:
    - address: 192.168.6.2/20
routes:
    - gateway: 192.168.1.1
